name: Update ArcGIS Gantt Data

on:
  schedule:
    - cron: "0 2 * * 1"  # every Monday at 2 AM UTC
  workflow_dispatch:       # allow manual trigger

permissions:
  contents: write  # ✅ 允许 GitHub Actions 推送到仓库

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ 避免旧 token 冲突

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas arcgis

      - name: Run ETL script
        env:
          ARCGIS_USERNAME: ${{ secrets.ARCGIS_USERNAME }}
          ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}
        run: |
          python Project_Management_ETL.py

      - name: Commit updated data.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data.json
          git commit -m "Auto update data.json" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main
